#!/usr/bin/env python3
"""Rebuild content/Cabinet of Digital Terms/Sources/Sources-Index.md from the
source files themselves — see CLAUDE.md, 'Sources-Index wordt gegenereerd'.

The index used to be kept by hand and drifted: on 2026-10-07 it listed 12
primary sources while the vault had more than 50. A list that can be derived
is derived. Reads every Term/Sources/*.md (except Sources/index.md), takes
title, source_role and the entry from the folder, and writes the two tables.

Run from the repo root: python3 scripts/build_sources_index.py
It also reports source files whose name does not follow Auteur-Term-Jaar.md
or Secondary-Termnaam.md (reported, not changed).
"""
import os
import re
import sys

VAULT = os.path.join(os.path.dirname(__file__), "..", "content", "Cabinet of Digital Terms")
OUT = os.path.join(VAULT, "Sources", "Sources-Index.md")


def frontmatter(path):
    with open(path, encoding="utf-8") as f:
        text = f.read()
    m = re.match(r"---\n(.*?)\n---", text, re.S)
    data = {}
    if m:
        for line in m.group(1).splitlines():
            k, _, v = line.partition(":")
            if v:
                data[k.strip()] = v.strip().strip('"')
    if "title" not in data:
        h = re.search(r"^## (\d+)\. ", text, re.M)
        data["items"] = str(len(re.findall(r"^## \d+\. ", text, re.M)))
    else:
        data["items"] = str(len(re.findall(r"^## \d+\. ", text, re.M)))
    return data


def main():
    primaries, bundles, odd = [], [], []
    for root, dirs, files in os.walk(VAULT):
        if os.path.basename(root) != "Sources" or os.path.abspath(root) == os.path.abspath(os.path.join(VAULT, "Sources")):
            continue
        entry = os.path.basename(os.path.dirname(root))
        for fname in sorted(files):
            if not fname.endswith(".md") or fname == "index.md" or fname.startswith("._"):
                continue
            fm = frontmatter(os.path.join(root, fname))
            role = fm.get("source_role", "")
            stem = fname[:-3]
            if role == "secondary" or stem.startswith("Secondary-"):
                bundles.append((entry, fname, fm.get("items", "?")))
                if not stem.startswith("Secondary-"):
                    odd.append(f"{entry}/{fname}")
            else:
                cite = re.sub(r"\s+—\s+.*$", "", fm.get("title", stem))
                primaries.append((cite, fm.get("source_type", ""), entry, fname))
                if not re.match(r"^[A-Za-z]+-[A-Za-z0-9]+-\d{4}$", stem):
                    odd.append(f"{entry}/{fname}")

    primaries.sort(key=lambda r: (r[2].lower(), r[0].lower()))
    bundles.sort(key=lambda r: r[0].lower())
    lines = [
        "---", 'title: "Sources Index"', "type: meta", "draft: true", "---", "",
        "# Sources Index", "",
        "Every source file in the vault, generated by `scripts/build_sources_index.py`; do not edit by hand. "
        "Check here before creating a new source file, so that a source cited in a second entry follows the "
        "naming rule (`Auteur-Term-Jaar.md`) instead of colliding with an existing file.", "",
        f"## Primary sources ({len(primaries)})", "",
        "| Citekey | Type | Entry | File |", "|---|---|---|---|",
    ]
    lines += [f"| {c} | {t} | {e} | `{f}` |" for c, t, e, f in primaries]
    lines += ["", f"## Secondary bundles ({len(bundles)})", "", "| Entry | File | Items |", "|---|---|---|"]
    lines += [f"| {e} | `{f}` | {n} |" for e, f, n in bundles]
    lines.append("")
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"{len(primaries)} primary sources, {len(bundles)} secondary bundles written.")
    for o in odd:
        print(f"name does not follow the rule: {o}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
